"""
Gives the index of which class it belongs too
Basically an input variable like "Private" is put into the function
Then the function returns the index of "workclass" which in this case is 1
"""


def getClassTypeIndex(classType):

	switcher = {
		"?": 1,
		"Federal-gov": 1,
		"Local-gov": 1,
		"Never-worked": 1,
		"Private": 1,
		"Self-emp-inc": 1,
		"Self-emp-not-inc": 1,
		"State-gov": 1,
		"Without-pay": 1,
		"10th": 3,
		"11th": 3,
		"12th": 3,
		"1st-4th": 3,
		"5th-6th": 3,
		"7th-8th": 3,
		"9th": 3,
		"Assoc-acdm": 3,
		"Assoc-voc": 3,
		"Bachelors": 3,
		"Doctorate": 3,
		"HS-grad": 3,
		"Masters": 3,
		"Preschool": 3,
		"Prof-school": 3,
		"Some-college": 3,
		"Divorced": 5,
		"Married-AF-spouse": 5,
		"Married-civ-spouse": 5,
		"Married-spouse-absent": 5,
		"Never-married": 5,
		"Separated": 5,
		"Widowed": 5,
		"?": 6,
		"Adm-clerical": 6,
		"Armed-Forces": 6,
		"Craft-repair": 6,
		"Exec-managerial": 6,
		"Farming-fishing": 6,
		"Handlers-cleaners": 6,
		"Machine-op-inspct": 6,
		"Other-service": 6,
		"Priv-house-serv": 6,
		"Prof-specialty": 6,
		"Protective-serv": 6,
		"Sales": 6,
		"Tech-support": 6,
		"Transport-moving": 6,
		"Husband": 7,
		"Not-in-family": 7,
		"Other-relative": 7,
		"Own-child": 7,
		"Unmarried": 7,
		"Wife": 7,
		"Amer-Indian-Eskimo": 8,
		"Asian-Pac-Islander": 8,
		"Black": 8,
		"Other": 8,
		"White": 8,
		"Female": 9,
		"Male": 9,
		"?": 13,
		"Cambodia": 13,
		"Canada": 13,
		"China": 13,
		"Columbia": 13,
		"Cuba": 13,
		"Dominican-Republic": 13,
		"Ecuador": 13,
		"El-Salvador": 13,
		"England": 13,
		"France": 13,
		"Germany": 13,
		"Greece": 13,
		"Guatemala": 13,
		"Haiti": 13,
		"Holand-Netherlands": 13,
		"Honduras": 13,
		"Hong": 13,
		"Hungary": 13,
		"India": 13,
		"Iran": 13,
		"Ireland": 13,
		"Italy": 13,
		"Jamaica": 13,
		"Japan": 13,
		"Laos": 13,
		"Mexico": 13,
		"Nicaragua": 13,
		"Outlying-US(Guam-USVI-etc)": 13,
		"Peru": 13,
		"Philippines": 13,
		"Poland": 13,
		"Portugal": 13,
		"Puerto-Rico": 13,
		"Scotland": 13,
		"South": 13,
		"Taiwan": 13,
		"Thailand": 13,
		"Trinadad&Tobago": 13,
		"United-States": 13,
		"Vietnam": 13,
		"Yugoslavia": 13,
		"<=50K": 14,
		">50K": 14
	}
	return switcher.get(classType, "")